// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import {
  frontmatter as fm0,
  toc as t0,
} from '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/.dumi/pages/theme-editor-cn/index.ts?type=frontmatter';
import {
  frontmatter as fm1,
  toc as t1,
} from '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/.dumi/pages/theme-editor/index.tsx?type=frontmatter';
import {
  frontmatter as fm2,
  toc as t2,
} from '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/.dumi/pages/index-cn/index.ts?type=frontmatter';
import {
  frontmatter as fm3,
  toc as t3,
} from '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/.dumi/pages/index/index.tsx?type=frontmatter';
import {
  frontmatter as fm4,
  toc as t4,
} from '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/_docs/react/contributing.en-US.md?type=frontmatter';
import { demoIndex as dmi4 } from '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/_docs/react/contributing.en-US.md?type=demo-index';
import {
  frontmatter as fm5,
  toc as t5,
} from '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/_docs/react/contributing.zh-CN.md?type=frontmatter';
import { demoIndex as dmi5 } from '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/_docs/react/contributing.zh-CN.md?type=demo-index';
import {
  frontmatter as fm6,
  toc as t6,
} from '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/_docs/react/introduce.en-US.md?type=frontmatter';
import { demoIndex as dmi6 } from '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/_docs/react/introduce.en-US.md?type=demo-index';
import {
  frontmatter as fm7,
  toc as t7,
} from '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/_docs/react/introduce.zh-CN.md?type=frontmatter';
import { demoIndex as dmi7 } from '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/_docs/react/introduce.zh-CN.md?type=demo-index';
import {
  frontmatter as fm8,
  toc as t8,
} from '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/CHANGELOG.zh-CN.md?type=frontmatter';
import { demoIndex as dmi8 } from '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/CHANGELOG.zh-CN.md?type=demo-index';
import {
  frontmatter as fm9,
  toc as t9,
} from '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/CHANGELOG.en-US.md?type=frontmatter';
import { demoIndex as dmi9 } from '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/CHANGELOG.en-US.md?type=demo-index';

export const filesMeta = {
  'theme-editor-cn/index': {
    frontmatter: fm0,
    toc: t0,
  },
  'theme-editor/index': {
    frontmatter: fm1,
    toc: t1,
  },
  'index-cn/index': {
    frontmatter: fm2,
    toc: t2,
  },
  'index/index': {
    frontmatter: fm3,
    toc: t3,
  },
  '_docs/react/contributing.en-US': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta____en-US" */ '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/_docs/react/contributing.en-US.md?type=text'
      ),
  },
  '_docs/react/contributing.zh-CN': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta____zh-CN" */ '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/_docs/react/contributing.zh-CN.md?type=text'
      ),
  },
  '_docs/react/introduce.en-US': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta____en-US" */ '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/_docs/react/introduce.en-US.md?type=text'
      ),
  },
  '_docs/react/introduce.zh-CN': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta____zh-CN" */ '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/_docs/react/introduce.zh-CN.md?type=text'
      ),
  },
  'changelog-cn': {
    frontmatter: fm8,
    toc: t8,
    demoIndex: dmi8,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__CHANGELOG.zh-CN.md__zh-CN" */ '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/CHANGELOG.zh-CN.md?type=text'
      ),
  },
  changelog: {
    frontmatter: fm9,
    toc: t9,
    demoIndex: dmi9,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__CHANGELOG.en-US.md__en-US" */ '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/CHANGELOG.en-US.md?type=text'
      ),
  },
};

export { tabs as tabsMeta } from './tabs';
