/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@bees-ui/core';


interface BeesWaveProps {
  
  /**  */
  disabled?: Components.BeesWave["disabled"]
}

interface BeesWaveEvents {
  
}

interface BeesWaveSlots {
  default: any
}
  
/* generated by Svelte v4.2.7 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import "svelte/internal/disclose-version";
import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let bees_wave;
	let current;
	const default_slot_template = /*#slots*/ ctx[4].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[3], null);

	return {
		c() {
			bees_wave = element("bees-wave");
			if (default_slot) default_slot.c();
			set_custom_element_data(bees_wave, "disabled", /*disabled*/ ctx[0]);
		},
		m(target, anchor) {
			insert(target, bees_wave, anchor);

			if (default_slot) {
				default_slot.m(bees_wave, null);
			}

			/*bees_wave_binding*/ ctx[5](bees_wave);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 8)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[3],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[3])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[3], dirty, null),
						null
					);
				}
			}

			if (!current || dirty & /*disabled*/ 1) {
				set_custom_element_data(bees_wave, "disabled", /*disabled*/ ctx[0]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) {
				detach(bees_wave);
			}

			if (default_slot) default_slot.d(detaching);
			/*bees_wave_binding*/ ctx[5](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { disabled = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(1, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function bees_wave_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(1, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('disabled' in $$props) $$invalidate(0, disabled = $$props.disabled);
		if ('$$scope' in $$props) $$invalidate(3, $$scope = $$props.$$scope);
	};

	return [disabled, __ref, getWebComponent, $$scope, slots, bees_wave_binding];
}

class BeesWave extends SvelteComponent {
  $$prop_def: BeesWaveProps;
  $$events_def: BeesWaveEvents;
  $$slot_def: BeesWaveSlots;

  $on<K extends keyof BeesWaveEvents>(type: K, callback: (e: BeesWaveEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<BeesWaveProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { disabled: 0, getWebComponent: 2 });
	}

	get getWebComponent(): HTMLBeesWaveElement | undefined {
		return this.$$.ctx[2];
	}
}

export default BeesWave;