/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@bees-ui/core';


interface BeesWaveEffectProps {
  
  /**  */
  target?: Components.BeesWaveEffect["target"]
  
  /**  */
  myClassName?: Components.BeesWaveEffect["myClassName"]
}

interface BeesWaveEffectEvents {
  
}

interface BeesWaveEffectSlots {
  default: any
}
  
/* generated by Svelte v4.2.7 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import "svelte/internal/disclose-version";
import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let bees_wave_effect;
	let current;
	const default_slot_template = /*#slots*/ ctx[6].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[5], null);

	return {
		c() {
			bees_wave_effect = element("bees-wave-effect");
			if (default_slot) default_slot.c();
			set_custom_element_data(bees_wave_effect, "my-class-name", /*myClassName*/ ctx[0]);
		},
		m(target, anchor) {
			insert(target, bees_wave_effect, anchor);

			if (default_slot) {
				default_slot.m(bees_wave_effect, null);
			}

			/*bees_wave_effect_binding*/ ctx[7](bees_wave_effect);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 32)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[5],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[5])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[5], dirty, null),
						null
					);
				}
			}

			if (!current || dirty & /*myClassName*/ 1) {
				set_custom_element_data(bees_wave_effect, "my-class-name", /*myClassName*/ ctx[0]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) {
				detach(bees_wave_effect);
			}

			if (default_slot) default_slot.d(detaching);
			/*bees_wave_effect_binding*/ ctx[7](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { target = undefined } = $$props;
	let { myClassName = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		$$invalidate(4, __mounted = true);
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(1, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function bees_wave_effect_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(1, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('target' in $$props) $$invalidate(2, target = $$props.target);
		if ('myClassName' in $$props) $$invalidate(0, myClassName = $$props.myClassName);
		if ('$$scope' in $$props) $$invalidate(5, $$scope = $$props.$$scope);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*__mounted, target*/ 20) {
			$: if (__mounted) setProp('target', target);
		}
	};

	return [
		myClassName,
		__ref,
		target,
		getWebComponent,
		__mounted,
		$$scope,
		slots,
		bees_wave_effect_binding
	];
}

class BeesWaveEffect extends SvelteComponent {
  $$prop_def: BeesWaveEffectProps;
  $$events_def: BeesWaveEffectEvents;
  $$slot_def: BeesWaveEffectSlots;

  $on<K extends keyof BeesWaveEffectEvents>(type: K, callback: (e: BeesWaveEffectEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<BeesWaveEffectProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			target: 2,
			myClassName: 0,
			getWebComponent: 3
		});
	}

	get getWebComponent(): HTMLBeesWaveEffectElement | undefined {
		return this.$$.ctx[3];
	}
}

export default BeesWaveEffect;