/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@bees-ui/core';


interface IkunLocaleProviderProps {
  
  /**  */
  locale?: Components.IkunLocaleProvider["locale"]
}

interface IkunLocaleProviderEvents {
  
}

interface IkunLocaleProviderSlots {
  default: any
}
  
/* generated by Svelte v4.2.7 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	safe_not_equal,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import "svelte/internal/disclose-version";
import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let ikun_locale_provider;
	let current;
	const default_slot_template = /*#slots*/ ctx[5].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[4], null);

	return {
		c() {
			ikun_locale_provider = element("ikun-locale-provider");
			if (default_slot) default_slot.c();
		},
		m(target, anchor) {
			insert(target, ikun_locale_provider, anchor);

			if (default_slot) {
				default_slot.m(ikun_locale_provider, null);
			}

			/*ikun_locale_provider_binding*/ ctx[6](ikun_locale_provider);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 16)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[4],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[4])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[4], dirty, null),
						null
					);
				}
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) {
				detach(ikun_locale_provider);
			}

			if (default_slot) default_slot.d(detaching);
			/*ikun_locale_provider_binding*/ ctx[6](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { locale = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		$$invalidate(3, __mounted = true);
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(0, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function ikun_locale_provider_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(0, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('locale' in $$props) $$invalidate(1, locale = $$props.locale);
		if ('$$scope' in $$props) $$invalidate(4, $$scope = $$props.$$scope);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*__mounted, locale*/ 10) {
			$: if (__mounted) setProp('locale', locale);
		}
	};

	return [
		__ref,
		locale,
		getWebComponent,
		__mounted,
		$$scope,
		slots,
		ikun_locale_provider_binding
	];
}

class IkunLocaleProvider extends SvelteComponent {
  $$prop_def: IkunLocaleProviderProps;
  $$events_def: IkunLocaleProviderEvents;
  $$slot_def: IkunLocaleProviderSlots;

  $on<K extends keyof IkunLocaleProviderEvents>(type: K, callback: (e: IkunLocaleProviderEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<IkunLocaleProviderProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { locale: 1, getWebComponent: 2 });
	}

	get getWebComponent(): HTMLIkunLocaleProviderElement | undefined {
		return this.$$.ctx[2];
	}
}

export default IkunLocaleProvider;