/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@ikunorg/core';


interface IkunConfigProviderProps {
  
  /**  */
  componentSize?: Components.IkunConfigProvider["componentSize"]
  
  /**  */
  theme?: Components.IkunConfigProvider["theme"]
  
  /**  */
  locale?: Components.IkunConfigProvider["locale"]
}

interface IkunConfigProviderEvents {
  
}

interface IkunConfigProviderSlots {
  default: any
}
  
/* generated by Svelte v4.2.7 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import "svelte/internal/disclose-version";
import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let ikun_config_provider;
	let current;
	const default_slot_template = /*#slots*/ ctx[7].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[6], null);

	return {
		c() {
			ikun_config_provider = element("ikun-config-provider");
			if (default_slot) default_slot.c();
			set_custom_element_data(ikun_config_provider, "component-size", /*componentSize*/ ctx[0]);
		},
		m(target, anchor) {
			insert(target, ikun_config_provider, anchor);

			if (default_slot) {
				default_slot.m(ikun_config_provider, null);
			}

			/*ikun_config_provider_binding*/ ctx[8](ikun_config_provider);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 64)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[6],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[6])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[6], dirty, null),
						null
					);
				}
			}

			if (!current || dirty & /*componentSize*/ 1) {
				set_custom_element_data(ikun_config_provider, "component-size", /*componentSize*/ ctx[0]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) {
				detach(ikun_config_provider);
			}

			if (default_slot) default_slot.d(detaching);
			/*ikun_config_provider_binding*/ ctx[8](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { componentSize = undefined } = $$props;
	let { theme = undefined } = $$props;
	let { locale = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		$$invalidate(5, __mounted = true);
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(1, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function ikun_config_provider_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(1, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('componentSize' in $$props) $$invalidate(0, componentSize = $$props.componentSize);
		if ('theme' in $$props) $$invalidate(2, theme = $$props.theme);
		if ('locale' in $$props) $$invalidate(3, locale = $$props.locale);
		if ('$$scope' in $$props) $$invalidate(6, $$scope = $$props.$$scope);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*__mounted, theme*/ 36) {
			$: if (__mounted) setProp('theme', theme);
		}

		if ($$self.$$.dirty & /*__mounted, locale*/ 40) {
			$: if (__mounted) setProp('locale', locale);
		}
	};

	return [
		componentSize,
		__ref,
		theme,
		locale,
		getWebComponent,
		__mounted,
		$$scope,
		slots,
		ikun_config_provider_binding
	];
}

class IkunConfigProvider extends SvelteComponent {
  $$prop_def: IkunConfigProviderProps;
  $$events_def: IkunConfigProviderEvents;
  $$slot_def: IkunConfigProviderSlots;

  $on<K extends keyof IkunConfigProviderEvents>(type: K, callback: (e: IkunConfigProviderEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<IkunConfigProviderProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			componentSize: 0,
			theme: 2,
			locale: 3,
			getWebComponent: 4
		});
	}

	get getWebComponent(): HTMLIkunConfigProviderElement | undefined {
		return this.$$.ctx[4];
	}
}

export default IkunConfigProvider;