/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@bees-ui/core';


interface MyComponentProps {
  
  /** The first name */
  first?: Components.MyComponent["first"]
  
  /** The middle name */
  middle?: Components.MyComponent["middle"]
  
  /** The last name */
  last?: Components.MyComponent["last"]
}

interface MyComponentEvents {
  
}

interface MyComponentSlots {
  default: any
}
  
/* generated by Svelte v4.2.7 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import "svelte/internal/disclose-version";
import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let my_component;
	let current;
	const default_slot_template = /*#slots*/ ctx[6].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[5], null);

	return {
		c() {
			my_component = element("my-component");
			if (default_slot) default_slot.c();
			set_custom_element_data(my_component, "first", /*first*/ ctx[0]);
			set_custom_element_data(my_component, "middle", /*middle*/ ctx[1]);
			set_custom_element_data(my_component, "last", /*last*/ ctx[2]);
		},
		m(target, anchor) {
			insert(target, my_component, anchor);

			if (default_slot) {
				default_slot.m(my_component, null);
			}

			/*my_component_binding*/ ctx[7](my_component);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 32)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[5],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[5])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[5], dirty, null),
						null
					);
				}
			}

			if (!current || dirty & /*first*/ 1) {
				set_custom_element_data(my_component, "first", /*first*/ ctx[0]);
			}

			if (!current || dirty & /*middle*/ 2) {
				set_custom_element_data(my_component, "middle", /*middle*/ ctx[1]);
			}

			if (!current || dirty & /*last*/ 4) {
				set_custom_element_data(my_component, "last", /*last*/ ctx[2]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) {
				detach(my_component);
			}

			if (default_slot) default_slot.d(detaching);
			/*my_component_binding*/ ctx[7](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { first = undefined } = $$props;
	let { middle = undefined } = $$props;
	let { last = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(3, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function my_component_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(3, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('first' in $$props) $$invalidate(0, first = $$props.first);
		if ('middle' in $$props) $$invalidate(1, middle = $$props.middle);
		if ('last' in $$props) $$invalidate(2, last = $$props.last);
		if ('$$scope' in $$props) $$invalidate(5, $$scope = $$props.$$scope);
	};

	return [
		first,
		middle,
		last,
		__ref,
		getWebComponent,
		$$scope,
		slots,
		my_component_binding
	];
}

class MyComponent extends SvelteComponent {
  $$prop_def: MyComponentProps;
  $$events_def: MyComponentEvents;
  $$slot_def: MyComponentSlots;

  $on<K extends keyof MyComponentEvents>(type: K, callback: (e: MyComponentEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<MyComponentProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			first: 0,
			middle: 1,
			last: 2,
			getWebComponent: 4
		});
	}

	get getWebComponent(): HTMLMyComponentElement | undefined {
		return this.$$.ctx[4];
	}
}

export default MyComponent;