/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SizeType, ThemeConfig } from "./components/config-provider/context";
import { Locale } from "@ikunorg/core/src/locale";
import { Locale as Locale1 } from "./locale";
export { SizeType, ThemeConfig } from "./components/config-provider/context";
export { Locale } from "@ikunorg/core/src/locale";
export { Locale as Locale1 } from "./locale";
export namespace Components {
    interface IkunButton {
        /**
          * If `true`, the user cannot interact with the button.
         */
        "disabled": boolean;
    }
    interface IkunConfigProvider {
        "componentSize": SizeType;
        "locale": Locale;
        "theme": ThemeConfig;
    }
    interface IkunLocaleProvider {
        "locale": Locale1;
    }
    interface IkunWave {
        "disabled": boolean;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLIkunButtonElement extends Components.IkunButton, HTMLStencilElement {
    }
    var HTMLIkunButtonElement: {
        prototype: HTMLIkunButtonElement;
        new (): HTMLIkunButtonElement;
    };
    interface HTMLIkunConfigProviderElement extends Components.IkunConfigProvider, HTMLStencilElement {
    }
    var HTMLIkunConfigProviderElement: {
        prototype: HTMLIkunConfigProviderElement;
        new (): HTMLIkunConfigProviderElement;
    };
    interface HTMLIkunLocaleProviderElement extends Components.IkunLocaleProvider, HTMLStencilElement {
    }
    var HTMLIkunLocaleProviderElement: {
        prototype: HTMLIkunLocaleProviderElement;
        new (): HTMLIkunLocaleProviderElement;
    };
    interface HTMLIkunWaveElement extends Components.IkunWave, HTMLStencilElement {
    }
    var HTMLIkunWaveElement: {
        prototype: HTMLIkunWaveElement;
        new (): HTMLIkunWaveElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ikun-button": HTMLIkunButtonElement;
        "ikun-config-provider": HTMLIkunConfigProviderElement;
        "ikun-locale-provider": HTMLIkunLocaleProviderElement;
        "ikun-wave": HTMLIkunWaveElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface IkunButton {
        /**
          * If `true`, the user cannot interact with the button.
         */
        "disabled"?: boolean;
    }
    interface IkunConfigProvider {
        "componentSize"?: SizeType;
        "locale"?: Locale;
        "theme"?: ThemeConfig;
    }
    interface IkunLocaleProvider {
        "locale"?: Locale1;
    }
    interface IkunWave {
        "disabled"?: boolean;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "ikun-button": IkunButton;
        "ikun-config-provider": IkunConfigProvider;
        "ikun-locale-provider": IkunLocaleProvider;
        "ikun-wave": IkunWave;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ikun-button": LocalJSX.IkunButton & JSXBase.HTMLAttributes<HTMLIkunButtonElement>;
            "ikun-config-provider": LocalJSX.IkunConfigProvider & JSXBase.HTMLAttributes<HTMLIkunConfigProviderElement>;
            "ikun-locale-provider": LocalJSX.IkunLocaleProvider & JSXBase.HTMLAttributes<HTMLIkunLocaleProviderElement>;
            "ikun-wave": LocalJSX.IkunWave & JSXBase.HTMLAttributes<HTMLIkunWaveElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
