// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export type {
  // server loader
  IServerLoaderArgs,
  UmiRequest,
  ServerLoader,
  // metadata loader
  MetadataLoader,
  IMetadata,
  IMetaTag,
} from '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/node_modules/.pnpm/@umijs+server@4.3.6/node_modules/@umijs/server/dist/types'
