// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import nprogress from '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/node_modules/.pnpm/nprogress@0.2.0/node_modules/nprogress';

import './nprogress.css';

import { useSiteData } from 'dumi';
import React, { useLayoutEffect, type FC } from 'preact/compat';

import UserLoading from '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/.dumi/loading.js';

const DumiLoading: FC = () => {
  const { setLoading } = useSiteData();

  useLayoutEffect(() => {
    setLoading(true);
    nprogress.start();

    return () => {
      setLoading(false);
      nprogress.done();
    };
  }, []);

  return <UserLoading />;
};

export default DumiLoading;
