// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {
    GlobalLayout: {
      id: 'GlobalLayout',
      path: '/',
      parentId: 'dumi-context-layout',
      isLayout: true,
      hasServerLoader: false,
      hasMetadataLoader: false,
    },
    'dumi-context-layout': {
      id: 'dumi-context-layout',
      path: '/',
      isLayout: true,
      hasServerLoader: false,
      hasMetadataLoader: false,
    },
    DocLayout: { id: 'DocLayout', path: '/', parentId: 'GlobalLayout', isLayout: true },
    'theme-editor-cn/index': {
      path: 'theme-editor-cn',
      id: 'theme-editor-cn/index',
      parentId: 'DocLayout',
      hasServerLoader: false,
      hasMetadataLoader: false,
    },
    'theme-editor/index': {
      path: 'theme-editor',
      id: 'theme-editor/index',
      parentId: 'DocLayout',
      hasServerLoader: false,
      hasMetadataLoader: false,
    },
    'index-cn/index': {
      path: 'index-cn',
      id: 'index-cn/index',
      parentId: 'DocLayout',
      hasServerLoader: false,
      hasMetadataLoader: false,
    },
    'index/index': {
      path: '',
      id: 'index/index',
      parentId: 'DocLayout',
      hasServerLoader: false,
      hasMetadataLoader: false,
    },
    '404/index': {
      path: '*',
      id: '404/index',
      parentId: 'DocLayout',
      hasServerLoader: false,
      hasMetadataLoader: false,
    },
    '_docs/react/contributing.en-US': {
      path: 'docs/react/contributing',
      id: '_docs/react/contributing.en-US',
      parentId: 'DocLayout',
    },
    '_docs/react/contributing.zh-CN': {
      path: 'docs/react/contributing-cn',
      id: '_docs/react/contributing.zh-CN',
      parentId: 'DocLayout',
    },
    '_docs/react/introduce.en-US': {
      path: 'docs/react/introduce',
      id: '_docs/react/introduce.en-US',
      parentId: 'DocLayout',
    },
    '_docs/react/introduce.zh-CN': {
      path: 'docs/react/introduce-cn',
      id: '_docs/react/introduce.zh-CN',
      parentId: 'DocLayout',
    },
    'demo-render': {
      id: 'demo-render',
      path: '~demos/:id',
      parentId: 'GlobalLayout',
      prerender: false,
    },
    'changelog-cn': { id: 'changelog-cn', path: 'changelog-cn', parentId: 'DocLayout' },
    changelog: { id: 'changelog', path: 'changelog', parentId: 'DocLayout' },
  } as const;
  return {
    routes,
    routeComponents: {
      GlobalLayout: React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__theme__layouts__GlobalLayout" */ '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/.dumi/theme/layouts/GlobalLayout.tsx'
          ),
      ),
      'dumi-context-layout': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__tmp-production__dumi__theme__ContextWrapper" */ '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/.dumi/tmp-production/dumi/theme/ContextWrapper'
          ),
      ),
      DocLayout: React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__theme__layouts__DocLayout__index" */ '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/.dumi/theme/layouts/DocLayout/index.tsx'
          ),
      ),
      'theme-editor-cn/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__pages__theme-editor-cn__index" */ '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/.dumi/pages/theme-editor-cn/index.ts'
          ),
      ),
      'theme-editor/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__pages__theme-editor__index" */ '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/.dumi/pages/theme-editor/index.tsx'
          ),
      ),
      'index-cn/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__pages__index-cn__index" */ '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/.dumi/pages/index-cn/index.ts'
          ),
      ),
      'index/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__pages__index__index" */ '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/.dumi/pages/index/index.tsx'
          ),
      ),
      '404/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__pages__404__index" */ '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/.dumi/pages/404/index.tsx'
          ),
      ),
      '_docs/react/contributing.en-US': React.lazy(
        () =>
          import(
            /* webpackChunkName: "_docs__react__contributing.en-US.md" */ '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/_docs/react/contributing.en-US.md'
          ),
      ),
      '_docs/react/contributing.zh-CN': React.lazy(
        () =>
          import(
            /* webpackChunkName: "_docs__react__contributing.zh-CN.md" */ '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/_docs/react/contributing.zh-CN.md'
          ),
      ),
      '_docs/react/introduce.en-US': React.lazy(
        () =>
          import(
            /* webpackChunkName: "_docs__react__introduce.en-US.md" */ '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/_docs/react/introduce.en-US.md'
          ),
      ),
      '_docs/react/introduce.zh-CN': React.lazy(
        () =>
          import(
            /* webpackChunkName: "_docs__react__introduce.zh-CN.md" */ '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/_docs/react/introduce.zh-CN.md'
          ),
      ),
      'demo-render': React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */ '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/node_modules/.pnpm/dumi@2.4.6_@babel+core@7.24.8_@swc+helpers@0.5.1_@types+node@20.14.10_@types+react@18.3.3_esl_mnrqy54fofpzh4toporgj5px7i/node_modules/dumi/dist/client/pages/Demo/index.js'
          ),
      ),
      'changelog-cn': React.lazy(
        () =>
          import(
            /* webpackChunkName: "CHANGELOG.zh-CN.md" */ '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/CHANGELOG.zh-CN.md'
          ),
      ),
      changelog: React.lazy(
        () =>
          import(
            /* webpackChunkName: "CHANGELOG.en-US.md" */ '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/docs/CHANGELOG.en-US.md'
          ),
      ),
    },
  };
}
