// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/node_modules/.pnpm/dumi-plugin-color-chunk@1.1.1_@babel+core@7.24.8_@swc+helpers@0.5.1_@types+node@20.14.10_@typ_lxq5h5w5rofieefka3bdrdgwwy/node_modules/dumi-plugin-color-chunk/es/component/index.js';
