// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/liuzhiwei/Desktop/workspeace/git-code/bees-ui/node_modules/.pnpm/dumi@2.4.6_@babel+core@7.24.8_@swc+helpers@0.5.1_@types+node@20.14.10_@types+react@18.3.3_esl_mnrqy54fofpzh4toporgj5px7i/node_modules/dumi/theme-default/slots/Content/index.js';
