[package]
name = "replace_script"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.5.0"
regex = "1.10.6"
serde_json = "1.0.128"
glob = "0.3.1"
git2 = "0.19.0"
tokio = { version = "1.40.0", features = ["full"] }
reqwest = "0.12.7"
lazy_static = "1.5.0"
colored = "2.1.0"
